apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-green
  labels:
    app: backend
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      version: green
  template:
    metadata:
      labels:
        app: backend
        version: green
    spec:
      containers:
      - name: backend
        image: tormenask/devops-final-backend:green
        ports:
        - containerPort: 3005
        env:
        - name: NODE_ENV
          value: development
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: "12345"
        - name: DB_NAME
          value: pokedex
        - name: DB_PORT
          value: "3306"
