services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=12345 
      - DB_NAME=pokedex
    depends_on:
      mysql:
        condition: service_healthy  
    restart: unless-stopped  
    command: sh -c "npm install && npm run dev"

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=12345  
      - MYSQL_DATABASE=pokedex
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data: