apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
  labels:
    app: backend
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: blue
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      containers:
      - name: backend
        image: tu-usuario/devops-final-backend:blue-latest
        ports:
        - containerPort: 3005
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "12345"
        - name: DB_NAME
          value: "pokedex"
        - name: JWT_SECRET
          value: "defaultsecretkey"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5 