apiVersion: v1
kind: Service
metadata:
  name: backend-blue-service
  labels:
    app: backend
    version: blue
spec:
  selector:
    app: backend
    version: blue
  ports:
  - port: 80
    targetPort: 3005
    protocol: TCP
  type: ClusterIP 