name: Build and Push Docker Image

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_REPOSITORY }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
        
    - name: Build and push Backend Blue
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY }}:blue-${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        
    - name: Build and push Backend Green
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY }}:green-${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1
          
    - name: Update latest tags
      run: |
        docker pull ${{ secrets.DOCKER_REPOSITORY }}:blue-${{ github.sha }}
        docker tag ${{ secrets.DOCKER_REPOSITORY }}:blue-${{ github.sha }} ${{ secrets.DOCKER_REPOSITORY }}:blue-latest
        docker push ${{ secrets.DOCKER_REPOSITORY }}:blue-latest
        
        docker pull ${{ secrets.DOCKER_REPOSITORY }}:green-${{ github.sha }}
        docker tag ${{ secrets.DOCKER_REPOSITORY }}:green-${{ github.sha }} ${{ secrets.DOCKER_REPOSITORY }}:green-latest
        docker push ${{ secrets.DOCKER_REPOSITORY }}:green-latest
